[2025-05-10T17:23:06.080+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: titanic_ml_pipeline.preprocess_data scheduled__2023-12-10T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
